# Generated by Django 5.0.2 on 2024-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
